[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }

# local crates
peer-discovery-core = { path = "./crates/core", version = "0.1.0" }